#!/bin/sh

# clean up derived files after every commit
# which helps prevent problems when switching branches
find . | grep '\.pyc$' | xargs rm
find . | grep --color=never '\~$' | grep -v 'backup~' | xargs rm -f
